import math
k = int(input("введите к "))
x = int(input("введите х "))
y = int(input("введите у "))
a = int(input("введите а"))
b = int(input("введите b"))
c = int(input("введите c"))
d = int(input("введите d"))
n = int(input("введите n"))
print("1)", 100**3-92**2+k)
print("2)", math.sqrt((1-math.cos(x))/2))
print("3)", (math.sqrt(abs(x)) * math.log(x**2)) / (-5 / 4*x + math.exp(x/2)))
print("4)", math.sqrt(math.sin(x)**2 + math.cos(y**3)**2))
print("5)", math.sqrt(x + math.sqrt(x**2+4*y**2)))
print("6)", math.exp(1/2) * (x - a))
print("7)", 1 / math.tan(x) - math.sin(math.sqrt(x**2+1)))
print("8)", 0.25 * (a - b) / (1/8 - abs(b)/(10**(n+3)+(math.log10(b)/(c-d)))))
